package edu.neu.anurag;

public enum ProductTypeEnum {

	ELECTRONICS, CLOTHING_FASHION, HOME_APPLIANCES, BEAUTY_PERSONAL_CARE, BOOKS_MEDIA, HEALTH_WELLNESS, TOYS_GAMES,
	FURNITURE_DECOR, GROCERIES_FOOD, SPORTS_OUTDOOR
}
